
export const COMMON = {
  SERVER_REQUEST: 'SERVER_REQUEST',
  SERVER_SUCCESS: 'SERVER_SUCCESS',
  REMOVE_ERRORS: 'REMOVE_ERRORS',
  SET_ERRORS: 'SET_ERRORS'
}

export const USER = {
  SIGNED_IN: 'SIGNED_IN',
  SIGNED_OUT: 'SIGNED_OUT',
  SET_PLAY_LIST: 'SET_PLAY_LIST',
  SET_ABOUT_COMPANY: 'SET_ABOUT_COMPANY',
  SET_CURRENT_PLAY: 'SET_CURRENT_PLAY'
}